targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: ja
          input_directory: lib/utils/i18n/input
          input_file_pattern: .i18n.yaml
          output_directory: lib/utils/i18n/output
          translate_var: i18n
          timestamp: false
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/{{dir}}/generated/{{file}}.freezed.dart'