name: yumemi_code_check
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_serializable: ^6.8.0
  riverpod_annotation: ^2.6.1
  slang: ^4.1.0
  slang_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  slang_build_runner: ^4.1.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true