name: jwt
on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
